language: java
jdk:
  - openjdk8

script: "mvn cobertura:cobertura"
after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: hive-custom-udfs
    skip_cleanup: true
    acl: public_read